conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("item/", include('item.urls')),

    path("singup/", views.singup, name="singup"),
    path("login/", auth_views.LoginView.as_view(template_name="core/login.html", authentication_form=LoginForm), name="login"),
    path('logout/', views.logoutPage, name="logout"),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | My Market</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">Poddle</a>
        <div class="space-x-6">
            <a href="{% url 'core:item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="{% url 'core:item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

            {% if request.user.is_authenticated %} 
            <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
            <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log out</a>
            {% else %}             
            <a href="{% url 'core:singup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
    {% block content %}

    {% endblock %}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>About</a></li>
                <li><a href="{% url 'core:contact' %}" class='text-lg text-teal-500 hover:text-teal-700'>Contact</a></li>
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Privacy policy</a></li>
                <li><a href='#' class='text-lg text-teal-500 hover:text-teal-700'>Term of use</a></li>
            </ul>
        </div>
    </footer>

</body>
</html>